server:
  port: 8001

spring:
  application:
    name: retail-bank-account-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
