server:
  port: 8001
  servlet:
    context-path: /retailBank
spring:
  application:
    name: retail-bank-account-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:retailBank
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

tagName : "Retail Bank Account management application"
